### ISSUE TITLE
environment variables for adjusting compilation

### ISSUE THREAD

**Issue by dagolden** [tokuhirom/Perl-Build#34]
Docs for plenv-install say this, but there is no such section or information that I could see:

```
For detailed information on installing Perl versions with
perl-build, including a list of environment variables for adjusting
compilation, see: https://github.com/tokuhirom/perl-build#usage
```

Being able to set defaults (e.g. "-j9") would be a really nice feature

**Comment by skaji** [comment]
I think this issue was fixed by #38
