### ISSUE TITLE
definitions appear as html

### ISSUE THREAD

**Issue by bestscarper** [tokuhirom/Perl-Build#46]
I tracked this issue via plenv...

```
perl-build --definitions
```

When running

```
perl-build --definitions
```

I sometimes get a truncated HTML listing.
It worked when I tried later. Bizarrely the only correlation I can find is that it fails which using a mobile data connection, and works on wifi.
Running OSX (Yosemite) with brewed plenv 2.1.0. System perl (5.18.2) and 5.22.2.

A short fragment of the output...

```
Available versions:
5.6.0.tar.gz">perl-5.6.0.tar.gz</a></td><td align="right">23-Mar-2000 07:06</td><td align="right">5.2M</td><td>&nbsp;</td></tr><tr><td valign="top"><img src="/icons/text.gif" alt="[TXT]"></td><td><a href="perl-5.6.0.tar.gz.md5.txt">perl-5.6.0.tar.gz.md5.txt</a></td><td align="right">17-Jun-2011 18:14</td><td align="right">32</td><td>&nbsp;</td></tr><tr><td valign="top"><img src="/icons/text.gif" alt="[TXT]"></td
```

**Comment by bestscarper** [comment]
It looks like the source HTML (http://www.cpan.org/src/5.0/) is coming back to me without newlines.
I wonder if my mobile provider is messing with the HTML en-route....

**Comment by syohex** [comment]
Could you check following patch ?

```diff
diff --git a/lib/Perl/Build.pm b/lib/Perl/Build.pm
index c6c5fc7..9da0ae1 100644
--- a/lib/Perl/Build.pm
+++ b/lib/Perl/Build.pm
@@ -32,8 +32,9 @@ sub available_perls {
     my @available_versions;
 
     my %uniq;
-    for ( split "\n", $html ) {
-        if (my ($version) = m|<a href="perl-(.+)\.tar\.gz">(.+?)</a>|) {
+    while ($html =~ m|<a href="perl-(.+?)\.tar\.gz">(.+?)</a>|g) {
+        my $version = $1;
+        if ($version) {
             next if $uniq{$version}++;
             push @available_versions, $version;
         }

```

**Comment by bestscarper** [comment]
No, but I found this worked, and still works with a "good" feed.

    diff --git a/lib/Perl/Build.pm b/lib/Perl/Build.pm
    index 988420b..78dad10 100644
    --- a/lib/Perl/Build.pm
    +++ b/lib/Perl/Build.pm
    @@ -32,11 +32,10 @@ sub available_perls {
         my @available_versions;

         my %uniq;
    -    for ( split "\n", $html ) {
    -        if (my ($version) = m|<a href="perl-(.+)\.tar\.gz">(.+?)</a>|) {
    -            next if $uniq{$version}++;
    -            push @available_versions, $version;
    -        }
    +    while ($html =~ m|<a href="perl-([^"]+)\.tar\.gz">(.+?)</a>|g) {
    +        my $version = $1;
    +        next if $uniq{$version}++;
    +        push @available_versions, $version;
         }

I would have provided a pull request, but I wasn't sure about generating the fat-packed version safely.

**Comment by tokuhirom** [comment]
you can send us a p-r without fatpacked one :P

**Comment by skaji** [comment]
I think this issue is resolved.
