### ISSUE TITLE
cperl support

### ISSUE THREAD

**Issue by moltar** [tokuhirom/Perl-Build#49]
Would it be possible to add cperl support? https://github.com/perl11/cperl
Thanks

**Comment by syohex** [comment]
cperl is already supported by https://github.com/tokuhirom/Perl-Build/pull/48. You can install cperl by following command with latest Perl-Build.

```
# You need to install IO::Socket::SSL
% plenv install --as cperl https://github.com/perl11/cperl/archive/cperl-5.22.1.tar.gz
```
