### ISSUE TITLE
Untar fails when file is compressed in xz format

### ISSUE THREAD

**Issue by orev** [tokuhirom/Perl-Build#50]
Installation fails when untarring a file with xz compression.  This is on CentOS 7.  Installing via "install" subcommand from plenv.

    Installing 5.22.0 as 5.22.0
    /usr/bin/perl -- /home/user/.plenv/plugins/perl-build/bin/perl-build --symlink-devel-executables --build-dir /home/user/.plenv/build/1442548125.3828/ --tarball-dir /home/user/.plenv/cache/ -Dusedevel -Dusethreads -Dman1dir=none -Dman3dir=none --jobs=9 --noman 5.22.0 /home/user/.plenv/versions/5.22.0
    Use the previously fetched perl-5.22.0.tar.xz

    gzip: stdin: not in gzip format
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    Failed to extract /home/user/.plenv/cache/perl-5.22.0.tar.xz at /home/user/.plenv/plugins/perl-build/bin/../lib//Perl/Build.pm line 54.
    ABORT

**Comment by syohex** [comment]
Please use gzip or bzip2 format. Perl-Build does not support xz format yet.

**Comment by orev** [comment]
I should have included the command line that I used.  I did not select the compression format, it is automatically selected when I install with a command like this:

    plenv install -j 9 -D usethreads -D man1dir=none -D man3dir=none --noman 5.22.0

5.22.0 seems to default to the xz format.

**Comment by syohex** [comment]
@orev I fixed at this issue at #51. Please update `perl-build` and retry. Please report us if you have still problems.
