### ISSUE TITLE
How to install cperl/stableperl from plenv CLI?

### ISSUE THREAD

**Issue by dolmen** [tokuhirom/Perl-Build#55]
I'm using perl-build from plenv.
I see some recent commits about support for cperl and stableperl.

How can I install cperl and stableperl from the plenv CLI?

**Comment by miyagawa** [comment]
plenv supports arbitrary URLs https://github.com/tokuhirom/Perl-Build/pull/43

**Comment by dolmen** [comment]
cperl:
```
plenv install --as=5.22.2-cperl https://github.com/perl11/cperl/releases/download/cperl-5.22.2/cperl-5.22.2.tar.bz2
```

Unfortunately `plenv install-cpanm` doesn't work for `cperl`.
