### ISSUE TITLE
Build perl without perl installed

### ISSUE THREAD

**Issue by z0rc** [tokuhirom/Perl-Build#57]
plenv-install is a perl script. I'm interested in case where the environment doesn't have a Perl installed (see https://fedoraproject.org/wiki/Changes/Build_Root_Without_Perl) and I want to install a perl via plenv. More or less the same way as rbenv allows to install ruby locally without depending on presence of system ruby at all.

**Comment by syohex** [comment]
Implementing perl-build in shell script makes maintenance too difficult. And I think shell script is not perfect. If we use some command which is not installed on your minimum platform, then you need to install it by `dnf install foo-bar`. This makes no differences to `dnf install perl`.

And we want to use [Devel::PatchPerl](https://github.com/bingos/devel-patchperl) for building Perl. It is Perl code. We need to re-implement in shell script it if we rewrite perl-build in shell script too. I think it is terrible.

I suppose plenv and perl-build are not suitable such minimum environment. I suppose to install from source code or to use pre-build binaries are better than plenv and perl-build on them.
