### ISSUE TITLE
Upgrade CPAN::Perl::Releases for perl 5.26.0

### ISSUE THREAD

**Issue by jhannah** [tokuhirom/Perl-Build#62]
It appears (line 9) that you've embedded CPAN-Perl-Releases-3.08 (6 months old).

https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build

So when we try to use Perl::Build for a perl 5.26.0 project, the request doesn't use the main CPAN mirrors, it [tries to find](https://metacpan.org/source/TOKUHIROM/Perl-Build-1.13/lib/Perl/Build.pm#L148) a link [from search.cpan.org](http://search.cpan.org/dist/perl-5.26.0/). search.cpan.org was down earlier today, so our project couldn't build.

**Comment by tokuhirom** [comment]
updated
