### ISSUE TITLE
Perl releases page is skipped when more than 3 days old

### ISSUE THREAD

**Issue by Grinnz** [tokuhirom/Perl-Build#66]
When trying to install a Perl:

    WARN: [perl_releases_page] This page is 3 or more days old. ignore

This caused issues when the fallback (search.cpan.org) mirror was not working. Is there any reason the Perl releases page should ever be considered out of date?

**Comment by anttilinno** [comment]
Hm, docker build fails with the same message.

**Comment by djzort** [comment]
repacking fixed this for me: author/fatpack.sh

**Comment by skaji** [comment]
Now current master (Perl-Build-1.20) uses MetaCPAN entirely.
