### ISSUE TITLE
Hardcoded URL in Perl::Build::perl_release_by_perl_releases_page gives outdated data

### ISSUE THREAD

**Issue by sjn** [tokuhirom/Perl-Build#73]
The URL in Perl::Build::perl_release_by_perl_releases_page for fetching a list of Perl releases is outdated.

outdated ---> http://perl-releases.s3-website-us-east-1.amazonaws.com

Maybe find an up-to-date canonical list somewhere else?

**Comment by skaji** [comment]
@sjn Thanks for reporting this.
Now current master (Perl-Build-1.20) uses MetaCPAN entirely, and I think this issue can be closed.
