### ISSUE TITLE
missing EUMM from the fat packed build script?

### ISSUE THREAD

**Issue by jjn1056** [tokuhirom/Perl-Build#82]
Hi,

I have some automation scripts that build docker images with Perl and Centos7 that have suddenly stopped working (or in the last month since the last time I built QA).  Here's the error:

[jjn@localhost ~]$ curl -L https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build | perl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--   6  717k    6 48310    0     0  80685      0  0:00:09 --:--:--  0:00:09  35  717k   35  255k    0     0   158k      0  0:00:04  0:00:01  0:00:03  66  717k   66  479k    0     0   182k      0  0:00:03  0:00:02  0:00:01 100  717k  100  717k    0     0   213k      0  0:00:03  0:00:03 --:--:--  213k
Can't locate ExtUtils/MakeMaker.pm in @INC (@INC contains: FatPacked::19839880=HASH(0x12ebb88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at - line 20.
Compilation failed in require at - line 8994.
BEGIN failed--compilation aborted at - line 8994.
Compilation failed in require at - line 9770.
BEGIN failed--compilation aborted at - line 9770.
[jjn@localhost ~]$

Now sadly Centos7 doesn't have EUMM with the built-in Perl, I have to install it separately with:

yum -y install perl-ExtUtils-MakeMaker

If I add that line to my build script the build pipeline go back to working fine.  So my problem solved :) but this might hit other people using Centos/Redhat.  I'm guessing that the newest fat packed version of "https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build" doesn't have EUMM in it and that older ones did, which is why I was getting away with it?  Happy to test for you if that sounds right and you make a fix. 

Thanks, and BTW this tool makes my life a lot easier!

john

**Comment by skaji** [comment]
@jjn1056 Fixed in current master branch. Thanks for reporting this!
