### ISSUE TITLE
Plenv or plenv-install to build to any directory, not just $(plenv root)/versions

### ISSUE THREAD

**Issue by mikkoi** [tokuhirom/Perl-Build#87]
Sometimes I need to create a totally isolated Perl environment, not just isolated module space (That I can do easily with `local::lib`). I often need to place the Perl into a special directory and mounted disk which is also mounted in other servers, whereas my home directory is not.

Currently it is only possible to compile and install new Perls under plenv root directory. Could we change the `plenv-install` plugin to make the above possible, maybe add a command line flag, e.g. _--install-dir_, or create another plugin for this, e.g. `plenv-isolated`, or `plenv-virtualenv` (in the style of Python `virtualenv` and `pyenv-virtualenv` plugin)? EDIT: `pyenv-virtualenv` only installs under `pyenv`, not the way we would like it. So, not a good example.

The installed Perl can be for install-and-forget type, or plenv can keep a list of the installed ones. Keeping the list and/or showing it together with `plenv-versions` requires a bit more work, so I'd beginning with install-and-forget would be quicker.

**Comment by skaji** [comment]
You can execute perl-build script directly.

**Comment by mikkoi** [comment]
Yes, but adding this functionality to plenv would benefit plenv and user because (at least I) went first to plenv to look for. Others might, too.

**Comment by skaji** [comment]
I think plenv should concentrate on perl installations in plenv root.

On the other hand, plenv allows users to create their own plugins.
So you can create your plugins as much as you want.
