### ISSUE TITLE
"No patch utility found" plenv install on fresh fedora 33

### ISSUE THREAD

**Issue by Simerax** [tokuhirom/Perl-Build#96]
I've just downloaded and installed plenv (2.3.1 commit: 77a7800) + perl-build (commit: e3965e5e340b52c210ffa52769fc6a29576b0083) like it is recommended for plenv.
I'm running a fresh fedora 33 installation with system Perl (5.32.0). 
I did have to install `perl-FindBin` `perl-locale` and `perl-deprecate` since they were missing in the system perl.

```
> plenv install 5.30.0
Installing 5.30.0 as 5.30.0
/usr/bin/perl -- /home/xaver/.plenv/plugins/perl-build/bin/perl-build --symlink-devel-executables --build-dir /home/xaver/.plenv/build/1606579152.16385/ --tarball-dir /home/xaver/.plenv/cache/ -Dversiononly 5.30.0 /home/xaver/.plenv/versions/5.30.0
Use the previously fetched perl-5.30.0.tar.gz
Configuring perl '5.30.0'
rm -f config.sh Policy.sh
Auto-guessed '5.30.0'
patching Configure
No patch utility found
ABORT
```

**Comment by skaji** [comment]
Install patch command first.

**Comment by Simerax** [comment]
Oh I thought this was a perl dependency
